export const dictSeedData: Record<string, { value: string; label: string; group?: string }[]> = {
  property_type: [
    { value: 'residential', label: '普通住宅' },
    { value: 'villa', label: '别墅' },
    { value: 'mixed', label: '商住两用' },
    { value: 'parking', label: '车位' },
    { value: 'shop', label: '商铺' },
    { value: 'office', label: '写字楼' },
    { value: 'factory', label: '厂房' },
    { value: 'land', label: '土地' },
  ],
  decoration_level: [
    { value: 'rough', label: '毛坯' },
    { value: 'simple', label: '清水' },
    { value: 'normal', label: '普装' },
    { value: 'fine', label: '精装' },
    { value: 'luxury', label: '豪装' },
  ],
  payment_method: [
    { value: 'monthly', label: '月付' },
    { value: 'bi_monthly', label: '二月付' },
    { value: 'quarterly', label: '季付' },
    { value: 'four_month', label: '四月付' },
    { value: 'half_year', label: '半年付' },
    { value: 'yearly', label: '年付' },
    { value: 'two_year', label: '二年付' },
    { value: 'three_year', label: '三年付' },
    { value: 'four_year', label: '四年付' },
    { value: 'full', label: '全额支付' },
    { value: 'irregular', label: '不规则缴费' },
  ],
  lease_term: [
    { value: '1_month', label: '1个月' },
    { value: '2_month', label: '2个月' },
    { value: '3_month', label: '3个月' },
    { value: 'half_year', label: '半年' },
    { value: '1_year', label: '1年' },
    { value: '2_year', label: '2年' },
    { value: '3_year', label: '3年' },
    { value: 'other', label: '其他' },
  ],
  room_type: [
    { value: 'master', label: '主卧' },
    { value: 'master_bath', label: '主卧独卫' },
    { value: 'second', label: '次卧' },
    { value: 'second_bath', label: '次卧独卫' },
    { value: 'small', label: '小卧' },
    { value: 'bright_partition', label: '明隔' },
    { value: 'dark_partition', label: '暗隔' },
    { value: 'bright_partition_bath', label: '明隔独卫' },
    { value: 'custom', label: '可自定义房型' },
  ],
  room_status: [
    { value: 'vacant', label: '空' },
    { value: 'rented', label: '已租' },
    { value: 'reserved', label: '定' },
    { value: 'checkout', label: '退' },
    { value: 'config', label: '配置' },
    { value: 'dirty', label: '脏房' },
    { value: 'repair', label: '维修' },
  ],
  source_channel: [
    { value: '58', label: '58同城' },
    { value: 'soufang', label: '搜房' },
    { value: 'ganji', label: '赶集' },
    { value: 'baixing', label: '百姓网' },
    { value: 'anjuke', label: '安居客' },
    { value: 'xianyu', label: '闲鱼' },
    { value: 'walk_in', label: '上门客' },
    { value: 'friend', label: '朋友介绍' },
    { value: 'call', label: '来电' },
    { value: 'old_customer', label: '老客户' },
    { value: 'peer', label: '同行' },
    { value: 'online', label: '网上联系' },
    { value: 'agency', label: '中介介绍' },
    { value: 'ads', label: '看到我们广告' },
  ],
  house_status: [
    { value: 'not_rented', label: '未租' },
    { value: 'rented', label: '已租' },
    { value: 'sold', label: '已售' },
    { value: 'pause', label: '暂不租' },
    { value: 'taken', label: '已拿房成交' },
    { value: 'signed', label: '已签约' },
    { value: 'deposit', label: '已交定' },
  ],
  disk_type: [
    { value: 'public', label: '公盘' },
    { value: 'private', label: '私盘' },
  ],
  demand_type: [
    { value: 'rent', label: '租房' },
    { value: 'sale', label: '买房' },
    { value: 'both', label: '租/买均可' },
  ],
  urgency: [
    { value: 'urgent', label: '紧急' },
    { value: 'normal', label: '一般' },
    { value: 'long_term', label: '长期' },
  ],
  customer_status: [
    { value: 'not_rented', label: '未租' },
    { value: 'rented', label: '已租' },
    { value: 'pause', label: '暂不租' },
    { value: 'no_answer', label: '电话未接听' },
    { value: 'to_shared', label: '转到合租' },
    { value: 'to_entire', label: '转到整租' },
    { value: 'to_central', label: '转到集中' },
    { value: 'deposit', label: '已定' },
  ],
  house_tag: [
    { value: 'subway', label: '近地铁' },
    { value: 'school', label: '学区房' },
    { value: 'parking', label: '有车位' },
    { value: 'elevator', label: '电梯房' },
    { value: 'garden', label: '花园洋房' },
    { value: 'new', label: '新上房源' },
    { value: 'urgent', label: '业主急售' },
    { value: 'bargain', label: '可议价' },
    { value: 'full_furniture', label: '家具齐全' },
    { value: 'south_facing', label: '朝南' },
    { value: 'north_south', label: '南北通透' },
    { value: 'high_floor', label: '高楼层' },
    { value: 'low_floor', label: '低楼层' },
    { value: 'quiet', label: '安静' },
    { value: 'central_ac', label: '中央空调' },
    { value: 'floor_heating', label: '地暖' },
    { value: 'fresh_air', label: '新风系统' },
    { value: 'smart_home', label: '智能家居' },
    { value: 'river_view', label: '江景房' },
    { value: 'park_view', label: '公园景观' },
    { value: 'city_view', label: '城市景观' },
    { value: 'sun_room', label: '阳光房' },
    { value: 'basement', label: '带地下室' },
    { value: 'loft', label: 'LOFT' },
    { value: 'duplex', label: '复式' },
    { value: 'villa', label: '独栋别墅' },
    { value: 'townhouse', label: '联排别墅' },
    { value: 'compound', label: '高端小区' },
  ],
  identity: [
    { value: 'tenant', label: '租客' },
    { value: 'landlord', label: '房东' },
    { value: 'shareholder', label: '股东' },
    { value: 'supplier', label: '供应商' },
    { value: 'decorator', label: '装修公司' },
    { value: 'property', label: '物业' },
    { value: 'other', label: '其他' },
  ],
  billing_category: [
    { value: 'property_fee', label: '物业费' },
    { value: 'rent_deposit', label: '房租或押金类收入' },
    { value: 'arrear', label: '欠款类收入' },
    { value: 'other_expense', label: '其他类支出' },
    { value: 'energy_income', label: '能源费用类收入' },
    { value: 'energy_expense', label: '能源费用类支出' },
    { value: 'unknown_income', label: '未知收入' },
    { value: 'other_income', label: '其他类收入' },
  ],
  plan_type: [
    { value: 'income', label: '应收' },
    { value: 'expense', label: '应支' },
  ],
  ticket_status: [
    { value: 'pending', label: '待处理' },
    { value: 'processing', label: '开票中' },
    { value: 'done', label: '已开票' },
    { value: 'rejected', label: '已驳回' },
    { value: 'failed', label: '开票失败' },
    { value: 'red', label: '已冲红' },
  ],
  payment_type: [
    { value: 'wechat', label: '微信' },
    { value: 'alipay', label: '支付宝' },
    { value: 'bank', label: '银行卡' },
    { value: 'cash', label: '现金' },
  ],
  card_type: [
    { value: 'personal', label: '对私' },
    { value: 'company', label: '对公' },
  ],
  biz_type: [
    { value: 'rent', label: '租房' },
    { value: 'sale', label: '售房' },
    { value: 'reserve', label: '储备' },
  ],
  orientation: [
    { value: 'south', label: '南' },
    { value: 'north', label: '北' },
    { value: 'east', label: '东' },
    { value: 'west', label: '西' },
    { value: 'south_north', label: '南北' },
    { value: 'south_west', label: '西南' },
    { value: 'south_east', label: '东南' },
    { value: 'north_west', label: '西北' },
    { value: 'north_east', label: '东北' },
    { value: 'east_west', label: '东西' },
  ],
  tax_type: [
    { value: 'personal', label: '个税' },
    { value: 'exempt', label: '免税' },
    { value: 'normal', label: '正常税' },
    { value: 'double', label: '双税' },
    { value: 'combined', label: '综合税' },
  ],
  certificate_type: [
    { value: 'property', label: '房产证' },
    { value: 'contract', label: '购房合同' },
    { value: 'agreement', label: '购房协议' },
    { value: 'other', label: '其他' },
  ],
  blacklist_type: [
    { value: 'tenant', label: '租客' },
    { value: 'landlord', label: '房东' },
    { value: 'supplier', label: '供应商' },
    { value: 'other', label: '其他' },
  ],
  blacklist_status: [
    { value: 'active', label: '生效中' },
    { value: 'revoked', label: '已撤销' },
  ],
};
