import type { RouteRecordRaw } from 'vue-router';

export const asyncRoutes: RouteRecordRaw[] = [
  {
    path: '/home',
    name: 'Home',
    component: () => import('@/views/dashboard/HomeView.vue'),
    meta: { title: '首页', permission: 'home' },
  },
  {
    path: '/house/rent',
    name: 'Rent',
    component: () => import('@/views/house/RentView.vue'),
    meta: { title: '租房管理', permission: 'house:rent' },
  },
  // 租房新增 - 不在菜单显示
  {
    path: '/house/rent/create',
    name: 'RentCreate',
    component: () => import('@/views/house/RentFormView.vue'),
    meta: { title: '新增租房', permission: 'house:rent', actionPermission: 'renting:add', hidden: true },
  },
  // 租房编辑 - 不在菜单显示
  {
    path: '/house/rent/edit/:id',
    name: 'RentEdit',
    component: () => import('@/views/house/RentFormView.vue'),
    meta: { title: '编辑租房', permission: 'house:rent', actionPermission: 'renting:edit', hidden: true },
  },
  {
    path: '/house/sale',
    name: 'Sale',
    component: () => import('@/views/house/SaleView.vue'),
    meta: { title: '售房管理', permission: 'house:sale' },
  },
  // 售房新增 - 不在菜单显示
  {
    path: '/house/sale/create',
    name: 'SaleCreate',
    component: () => import('@/views/house/SaleFormView.vue'),
    meta: { title: '新增售房', permission: 'house:sale', actionPermission: 'sale:add', hidden: true },
  },
  {
    path: '/house/sale/edit/:id',
    name: 'SaleEdit',
    component: () => import('@/views/house/SaleFormView.vue'),
    meta: { title: '编辑售房', permission: 'house:sale', actionPermission: 'sale:edit', hidden: true },
  },
  {
    path: '/house/reserve-house',
    name: 'ReserveHouse',
    component: () => import('@/views/house/ReserveHouseView.vue'),
    meta: { title: '储备房源', permission: 'house:reserve_house' },
  },
  {
    path: '/house/reserve-house/create',
    name: 'ReserveHouseCreate',
    component: () => import('@/views/house/ReserveHouseFormView.vue'),
    meta: { title: '新增储备房源', permission: 'house:reserve_house', actionPermission: 'reserve:house:add', hidden: true },
  },
  {
    path: '/house/reserve-house/edit/:id',
    name: 'ReserveHouseEdit',
    component: () => import('@/views/house/ReserveHouseFormView.vue'),
    meta: { title: '编辑储备房源', permission: 'house:reserve_house', actionPermission: 'reserve:house:add', hidden: true },
  },
  {
    path: '/house/reserve-client',
    name: 'ReserveClient',
    component: () => import('@/views/house/ReserveClientView.vue'),
    meta: { title: '储备客源', permission: 'house:reserve_client' },
  },
  {
    path: '/house/reserve-client/create',
    name: 'ReserveClientCreate',
    component: () => import('@/views/house/ReserveClientFormView.vue'),
    meta: { title: '新增储备客源', permission: 'house:reserve_client', actionPermission: 'reserve:client:add', hidden: true },
  },
  {
    path: '/house/reserve-client/edit/:id',
    name: 'ReserveClientEdit',
    component: () => import('@/views/house/ReserveClientFormView.vue'),
    meta: { title: '编辑储备客源', permission: 'house:reserve_client', actionPermission: 'reserve:client:add', hidden: true },
  },
  {
    path: '/house/customer',
    name: 'Customer',
    component: () => import('@/views/house/CustomerView.vue'),
    meta: { title: '客户管理', permission: 'house:customer' },
  },
  {
    path: '/house/customer/create',
    name: 'CustomerCreate',
    component: () => import('@/views/house/CustomerFormView.vue'),
    meta: { title: '新增客户', permission: 'house:customer', actionPermission: 'house:customer:create', hidden: true },
  },
  {
    path: '/house/customer/edit/:id',
    name: 'CustomerEdit',
    component: () => import('@/views/house/CustomerFormView.vue'),
    meta: { title: '编辑客户', permission: 'house:customer', actionPermission: 'house:customer:edit', hidden: true },
  },
  {
    path: '/house/blacklist',
    name: 'Blacklist',
    component: () => import('@/views/house/BlacklistView.vue'),
    meta: { title: '黑名单', permission: 'house:blacklist' },
  },
  {
    path: '/house/blacklist/create',
    name: 'BlacklistCreate',
    component: () => import('@/views/house/BlacklistFormView.vue'),
    meta: { title: '新增黑名单', permission: 'house:blacklist', actionPermission: 'house:blacklist:create', hidden: true },
  },
  {
    path: '/house/blacklist/edit/:id',
    name: 'BlacklistEdit',
    component: () => import('@/views/house/BlacklistFormView.vue'),
    meta: { title: '编辑黑名单', permission: 'house:blacklist', actionPermission: 'house:blacklist:edit', hidden: true },
  },
  {
    path: '/house/community',
    name: 'Community',
    component: () => import('@/views/house/CommunityView.vue'),
    meta: { title: '小区管理', permission: 'house:community' },
  },
  {
    path: '/house/community/create',
    name: 'CommunityCreate',
    component: () => import('@/views/house/CommunityFormView.vue'),
    meta: { title: '新增小区', permission: 'house:community', actionPermission: 'house:community:create', hidden: true },
  },
  {
    path: '/house/community/edit/:id',
    name: 'CommunityEdit',
    component: () => import('@/views/house/CommunityFormView.vue'),
    meta: { title: '编辑小区', permission: 'house:community', actionPermission: 'house:community:edit', hidden: true },
  },
  {
    path: '/house/wizard',
    name: 'HouseWizard',
    component: () => import('@/views/wizard/HouseWizardView.vue'),
    meta: { title: '房源录入', permission: ['house:rent', 'house:sale', 'house:reserve_house'], actionPermission: ['renting:add', 'sale:add', 'reserve:house:add'], hidden: true },
  },
  // ---- Finance ----
  {
    path: '/finance/bill',
    name: 'FinanceBill',
    component: () => import('@/views/finance/BillView.vue'),
    meta: { title: '账单', permission: 'finance:bill' },
  },
  {
    path: '/finance/bill/create',
    name: 'FinanceBillCreate',
    component: () => import('@/views/finance/BillFormView.vue'),
    meta: { title: '新增账单', permission: 'finance:bill', actionPermission: 'finance:bill:modify', hidden: true },
  },
  {
    path: '/finance/bill/edit/:id',
    name: 'FinanceBillEdit',
    component: () => import('@/views/finance/BillFormView.vue'),
    meta: { title: '编辑账单', permission: 'finance:bill', actionPermission: 'finance:bill:modify', hidden: true },
  },
  {
    path: '/finance/daily-account',
    name: 'FinanceFlow',
    component: () => import('@/views/finance/FlowView.vue'),
    meta: { title: '流水账', permission: 'finance:flow' },
  },
  {
    path: '/finance/daily-account/create',
    name: 'FinanceFlowCreate',
    component: () => import('@/views/finance/FlowFormView.vue'),
    meta: { title: '新增流水', permission: 'finance:flow', actionPermission: 'finance:flow:modify', hidden: true },
  },
  {
    path: '/finance/daily-account/edit/:id',
    name: 'FinanceFlowEdit',
    component: () => import('@/views/finance/FlowFormView.vue'),
    meta: { title: '编辑流水', permission: 'finance:flow', actionPermission: 'finance:flow:modify', hidden: true },
  },
  {
    path: '/finance/rent-increase',
    name: 'FinanceRentIncrease',
    component: () => import('@/views/finance/RentIncreaseView.vue'),
    meta: { title: '涨价统计', permission: 'finance:rent_increase' },
  },
  {
    path: '/finance/profit',
    name: 'FinanceProfit',
    component: () => import('@/views/finance/ProfitView.vue'),
    meta: { title: '公寓利润', permission: 'finance:profit' },
  },
  {
    path: '/finance/partner',
    name: 'FinancePartner',
    component: () => import('@/views/finance/PartnerView.vue'),
    meta: { title: '合伙人', permission: 'finance:partner' },
  },
  {
    path: '/finance/income-cost',
    name: 'FinanceIncomeCost',
    component: () => import('@/views/finance/IncomeCostView.vue'),
    meta: { title: '收入成本', permission: 'finance:income_cost' },
  },
  {
    path: '/finance/performance',
    name: 'FinancePerformance',
    component: () => import('@/views/finance/PerformanceView.vue'),
    meta: { title: '业绩核算', permission: 'finance:performance' },
  },
  {
    path: '/finance/accounting',
    name: 'FinanceAccounting',
    component: () => import('@/views/finance/AccountingView.vue'),
    meta: { title: '财务核算', permission: 'finance:accounting' },
  },
  {
    path: '/finance/arrears',
    name: 'FinanceArrears',
    component: () => import('@/views/finance/ArrearsView.vue'),
    meta: { title: '欠款统计', permission: 'finance:arrears' },
  },
  {
    path: '/finance/plan',
    name: 'FinancePlan',
    component: () => import('@/views/finance/PlanView.vue'),
    meta: { title: '收支计划', permission: 'finance:plan' },
  },
  {
    path: '/finance/plan/create',
    name: 'FinancePlanCreate',
    component: () => import('@/views/finance/PlanFormView.vue'),
    meta: { title: '新增计划', permission: 'finance:plan', actionPermission: 'finance:bill:modify', hidden: true },
  },
  {
    path: '/finance/payout',
    name: 'FinancePayout',
    component: () => import('@/views/finance/PayoutView.vue'),
    meta: { title: '代付管理', permission: 'finance:payout' },
  },
  {
    path: '/finance/payout/create',
    name: 'FinancePayoutCreate',
    component: () => import('@/views/finance/PayoutFormView.vue'),
    meta: { title: '新增代付', permission: 'finance:payout', actionPermission: 'finance:payout:create', hidden: true },
  },
  {
    path: '/finance/billing',
    name: 'FinanceBilling',
    component: () => import('@/views/finance/BillingView.vue'),
    meta: { title: '开票管理', permission: 'finance:billing' },
  },
  {
    path: '/finance/billing/create',
    name: 'FinanceBillingCreate',
    component: () => import('@/views/finance/BillingFormView.vue'),
    meta: { title: '新增开票', permission: 'finance:billing', actionPermission: 'finance:ticket:apply', hidden: true },
  },
  // ---- System ----
  {
    path: '/system/role',
    name: 'SystemRole',
    component: () => import('@/views/system/RoleView.vue'),
    meta: { title: '角色管理', permission: 'system:role' },
  },
  {
    path: '/system/role/create',
    name: 'SystemRoleCreate',
    component: () => import('@/views/system/RoleFormView.vue'),
    meta: { title: '新增角色', permission: 'system:role', actionPermission: 'system:role:create', hidden: true },
  },
  {
    path: '/system/permission',
    name: 'SystemPermission',
    component: () => import('@/views/system/PermissionView.vue'),
    meta: { title: '权限管理', permission: 'system:permission' },
  },
  {
    path: '/system/dictionary',
    name: 'SystemDictionary',
    component: () => import('@/views/system/DictionaryView.vue'),
    meta: { title: '字典管理', permission: 'system:dictionary' },
  },
  {
    path: '/system/dictionary/create',
    name: 'SystemDictionaryCreate',
    component: () => import('@/views/system/DictionaryFormView.vue'),
    meta: { title: '新增字典', permission: 'system:dictionary', actionPermission: 'system:dictionary:edit', hidden: true },
  },
  {
    path: '/system/employee',
    name: 'SystemEmployee',
    component: () => import('@/views/system/EmployeeView.vue'),
    meta: { title: '人员管理', permission: 'system:employee' },
  },
  {
    path: '/system/employee/create',
    name: 'SystemEmployeeCreate',
    component: () => import('@/views/system/EmployeeFormView.vue'),
    meta: { title: '新增人员', permission: 'system:employee', actionPermission: 'system:employee:edit', hidden: true },
  },
  {
    path: '/system/employee/edit/:id',
    name: 'SystemEmployeeEdit',
    component: () => import('@/views/system/EmployeeFormView.vue'),
    meta: { title: '编辑人员', permission: 'system:employee', actionPermission: 'system:employee:edit', hidden: true },
  },
  {
    path: '/system/store',
    name: 'SystemStore',
    component: () => import('@/views/system/StoreView.vue'),
    meta: { title: '门店管理', permission: 'system:store' },
  },
  {
    path: '/system/store/create',
    name: 'SystemStoreCreate',
    component: () => import('@/views/system/StoreFormView.vue'),
    meta: { title: '新增门店', permission: 'system:store', actionPermission: 'system:store:edit', hidden: true },
  },
  {
    path: '/system/store/edit/:id',
    name: 'SystemStoreEdit',
    component: () => import('@/views/system/StoreFormView.vue'),
    meta: { title: '编辑门店', permission: 'system:store', actionPermission: 'system:store:edit', hidden: true },
  },
  {
    path: '/system/log',
    name: 'SystemLog',
    component: () => import('@/views/system/LogView.vue'),
    meta: { title: '操作日志', permission: 'system:log' },
  },
  {
    path: '/system/config',
    name: 'SystemConfig',
    component: () => import('@/views/system/ConfigView.vue'),
    meta: { title: '系统配置', permission: 'system:config' },
  },
  {
    path: '/house/checkout',
    name: 'HouseCheckout',
    component: () => import('@/views/house/CheckoutView.vue'),
    meta: { title: '退租管理', permission: 'house:checkout' },
  },
  {
    path: '/house/deposit',
    name: 'HouseDeposit',
    component: () => import('@/views/house/DepositView.vue'),
    meta: { title: '押金管理', permission: 'house:deposit' },
  },
];
