import type { RouteRecordRaw } from 'vue-router';

export const asyncRoutes: RouteRecordRaw[] = [
  {
    path: '/home',
    name: 'Home',
    component: () => import('@/views/dashboard/HomeView.vue'),
    meta: { title: '首页', permission: 'home' },
  },
  {
    path: '/house/rent',
    name: 'Rent',
    component: () => import('@/views/house/RentView.vue'),
    meta: { title: '租房管理', permission: 'house:rent' },
  },
  {
    path: '/house/sale',
    name: 'Sale',
    component: () => import('@/views/house/SaleView.vue'),
    meta: { title: '售房管理', permission: 'house:sale' },
  },
  {
    path: '/house/reserve-house',
    name: 'ReserveHouse',
    component: () => import('@/views/house/ReserveHouseView.vue'),
    meta: { title: '储备房源', permission: 'house:reserve_house' },
  },
  {
    path: '/house/reserve-client',
    name: 'ReserveClient',
    component: () => import('@/views/house/ReserveClientView.vue'),
    meta: { title: '储备客源', permission: 'house:reserve_client' },
  },
  {
    path: '/house/customer',
    name: 'Customer',
    component: () => import('@/views/house/CustomerView.vue'),
    meta: { title: '客户管理', permission: 'house:customer' },
  },
  {
    path: '/house/blacklist',
    name: 'Blacklist',
    component: () => import('@/views/house/BlacklistView.vue'),
    meta: { title: '黑名单', permission: 'house:customer' },
  },
  {
    path: '/house/community',
    name: 'Community',
    component: () => import('@/views/house/CommunityView.vue'),
    meta: { title: '小区管理', permission: 'house:community' },
  },
  {
    path: '/house/wizard',
    name: 'HouseWizard',
    component: () => import('@/views/wizard/HouseWizardView.vue'),
    meta: { title: '房源录入', permission: 'house:rent' },
  },
  {
    path: '/finance/bill',
    name: 'FinanceBill',
    component: () => import('@/views/finance/BillView.vue'),
    meta: { title: '账单', permission: 'finance:bill' },
  },
  {
    path: '/finance/daily-account',
    name: 'FinanceFlow',
    component: () => import('@/views/finance/FlowView.vue'),
    meta: { title: '流水账', permission: 'finance:flow' },
  },
  {
    path: '/finance/rent-increase',
    name: 'FinanceRentIncrease',
    component: () => import('@/views/finance/RentIncreaseView.vue'),
    meta: { title: '涨价统计', permission: 'finance:rent_increase' },
  },
  {
    path: '/finance/profit',
    name: 'FinanceProfit',
    component: () => import('@/views/finance/ProfitView.vue'),
    meta: { title: '公寓利润', permission: 'finance:profit' },
  },
  {
    path: '/finance/partner',
    name: 'FinancePartner',
    component: () => import('@/views/finance/PartnerView.vue'),
    meta: { title: '合伙人', permission: 'finance:partner' },
  },
  {
    path: '/finance/income-cost',
    name: 'FinanceIncomeCost',
    component: () => import('@/views/finance/IncomeCostView.vue'),
    meta: { title: '收入成本', permission: 'finance:income_cost' },
  },
  {
    path: '/finance/performance',
    name: 'FinancePerformance',
    component: () => import('@/views/finance/PerformanceView.vue'),
    meta: { title: '业绩核算', permission: 'finance:performance' },
  },
  {
    path: '/finance/accounting',
    name: 'FinanceAccounting',
    component: () => import('@/views/finance/AccountingView.vue'),
    meta: { title: '财务核算', permission: 'finance:accounting' },
  },
  {
    path: '/finance/arrears',
    name: 'FinanceArrears',
    component: () => import('@/views/finance/ArrearsView.vue'),
    meta: { title: '欠款统计', permission: 'finance:arrears' },
  },
  {
    path: '/finance/plan',
    name: 'FinancePlan',
    component: () => import('@/views/finance/PlanView.vue'),
    meta: { title: '收支计划', permission: 'finance:plan' },
  },
  {
    path: '/finance/payout',
    name: 'FinancePayout',
    component: () => import('@/views/finance/PayoutView.vue'),
    meta: { title: '代付管理', permission: 'finance:payout' },
  },
  {
    path: '/finance/billing',
    name: 'FinanceBilling',
    component: () => import('@/views/finance/BillingView.vue'),
    meta: { title: '开票管理', permission: 'finance:billing' },
  },
  {
    path: '/system/role',
    name: 'SystemRole',
    component: () => import('@/views/system/RoleView.vue'),
    meta: { title: '角色管理', permission: 'system:role' },
  },
  {
    path: '/system/permission',
    name: 'SystemPermission',
    component: () => import('@/views/system/PermissionView.vue'),
    meta: { title: '权限管理', permission: 'system:permission' },
  },
  {
    path: '/system/dictionary',
    name: 'SystemDictionary',
    component: () => import('@/views/system/DictionaryView.vue'),
    meta: { title: '字典管理', permission: 'system:dictionary' },
  },
  {
    path: '/system/employee',
    name: 'SystemEmployee',
    component: () => import('@/views/system/EmployeeView.vue'),
    meta: { title: '人员管理', permission: 'system:employee' },
  },
];
